import React, { useEffect, useState } from "react";
import { CalendarDays, Plus, Trash2, TrendingUp, TrendingDown, IndianRupee, WalletCards } from "lucide-react";
import { adminApi, apiError } from "../lib/api";
import { inr } from "../lib/utils";
import { toast } from "sonner";
import { Modal, Field, inputCls, PageHead } from "./ui";

function money(v) { return inr(Number(v || 0)); }
function formatPct(v) { return `${Number(v || 0).toFixed(1)}%`; }
function presetRange(preset) {
  const end = new Date(); const start = new Date(end);
  if (preset === "today") start.setHours(0,0,0,0);
  else if (preset === "week") { const d = (end.getDay() + 6) % 7; start.setDate(end.getDate() - d); start.setHours(0,0,0,0); }
  else if (preset === "month") { start.setDate(1); start.setHours(0,0,0,0); }
  else if (preset === "last_month") { start.setMonth(start.getMonth()-1,1); start.setHours(0,0,0,0); end.setDate(0); end.setHours(23,59,59,999); }
  return { from: start.toISOString().slice(0,10), to: end.toISOString().slice(0,10) };
}

export default function Pnl() {
  const [preset,setPreset] = useState("month"); const [from,setFrom] = useState(presetRange("month").from); const [to,setTo] = useState(presetRange("month").to);
  const [data,setData] = useState(null); const [expenses,setExpenses] = useState([]); const [showExpense,setShowExpense] = useState(false); const [saving,setSaving] = useState(false); const [form,setForm] = useState({category:"Shipping", amount:"", note:"", date:new Date().toISOString().slice(0,10)});

  const load = async () => {
    try { const [{data:d},{data:e}] = await Promise.all([adminApi.get(`/pnl/summary?from=${from}&to=${to}`), adminApi.get(`/pnl/expenses?from=${from}&to=${to}`)]); setData(d); setExpenses(e.items || []); }
    catch (err) { toast.error(apiError(err)); }
  };
  useEffect(() => { load(); }, [from,to]);
  const choose = (p) => { setPreset(p); if (p !== "custom") { const r=presetRange(p); setFrom(r.from); setTo(r.to); } };
  const saveExpense = async () => { const amt=Number(form.amount||0); if(amt<=0) return toast.error("Enter a valid expense amount."); setSaving(true); try { await adminApi.post("/pnl/expenses", {...form,amount:amt}); toast.success("Expense added"); setShowExpense(false); setForm({category:"Shipping",amount:"",note:"",date:new Date().toISOString().slice(0,10)}); load(); } catch(e){toast.error(apiError(e));} finally{setSaving(false);} };
  const removeExpense = async (id) => { try { await adminApi.delete(`/pnl/expenses/${id}`); toast.success("Expense removed"); load(); } catch(e){toast.error(apiError(e));} };

  if (!data) return <div className="py-16 text-center text-gray-500">Loading P&L…</div>;
  const cards = [["Total Sales",money(data.sales),IndianRupee,""],["Net Revenue",money(data.net_revenue),TrendingUp,""],["COGS",money(data.cogs),WalletCards,""],["Expenses",money(data.expenses),WalletCards,""],["Gross Profit",money(data.gross_profit),TrendingUp,""],["Net Profit",money(data.net_profit),data.net_profit>=0?TrendingUp:TrendingDown,""],["Profit Margin",formatPct(data.profit_margin),TrendingUp,""]];
  return <div>
    <PageHead title="Profit & Loss" subtitle="Simple commerce P&L using orders, refunds, product purchase costs and business expenses" action={<button onClick={()=>setShowExpense(true)} className="px-4 py-2 rounded-lg bg-plum text-white text-sm flex items-center gap-2"><Plus size={15}/> Add Expense</button>} />
    <div className="bg-white rounded-2xl border border-gray-200 p-4 mb-6 flex flex-wrap gap-2 items-center"><div className="flex items-center gap-2 text-sm text-gray-600 mr-2"><CalendarDays size={15}/> Period</div>{[["today","Today"],["week","This Week"],["month","This Month"],["last_month","Last Month"],["custom","Custom Range"]].map(([v,l])=><button key={v} onClick={()=>choose(v)} className={`px-3 py-1.5 rounded-lg text-sm border ${preset===v?"bg-plum text-white border-plum":"border-gray-300 text-gray-700 bg-white"}`}>{l}</button>)}{preset==="custom"&&<><input type="date" value={from} onChange={e=>setFrom(e.target.value)} className={inputCls+" w-auto"}/><span className="text-gray-400">to</span><input type="date" value={to} onChange={e=>setTo(e.target.value)} className={inputCls+" w-auto"}/></>}</div>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-6">{cards.map(([label,value,Icon])=><div key={label} className="bg-white rounded-2xl border border-gray-200 p-5"><div className="flex items-center justify-between"><p className="text-xs text-gray-500">{label}</p><span className="w-8 h-8 rounded-lg bg-plum/10 text-plum flex items-center justify-center"><Icon size={15}/></span></div><p className={`text-2xl font-semibold mt-2 ${label==='Net Profit' && data.net_profit<0?'text-red-600':'text-gray-900'}`}>{value}</p></div>)}</div>
    <div className="grid lg:grid-cols-3 gap-5 mb-6">
      <div className="lg:col-span-2 bg-white rounded-2xl border border-gray-200 p-5"><div className="flex items-center justify-between mb-5"><div><p className="font-semibold">Sales, Expenses & Profit</p><p className="text-xs text-gray-400 mt-1">Selected period</p></div></div><div className="space-y-3">{data.series.map((s)=><div key={s.period} className="grid grid-cols-[95px_1fr] gap-3 items-center"><p className="text-xs text-gray-500">{s.period}</p><div className="space-y-1"><div className="h-2 bg-gray-100 rounded-full overflow-hidden"><div className="h-2 bg-plum rounded-full" style={{width:`${Math.min(100, data.max_sales ? s.sales/data.max_sales*100 : 0)}%`}}/></div><div className="flex justify-between text-[11px] text-gray-400"><span>Sales {money(s.sales)}</span><span>Profit {money(s.net_profit)}</span></div></div></div>)}</div></div>
      <div className="bg-white rounded-2xl border border-gray-200 p-5"><p className="font-semibold">Expense mix</p><div className="mt-4 space-y-3">{data.expense_breakdown.length===0?<p className="text-sm text-gray-400">No expenses added.</p>:data.expense_breakdown.map(e=><div key={e.category} className="flex justify-between text-sm"><span>{e.category}</span><b>{money(e.amount)}</b></div>)}</div></div>
    </div>
    <div className="bg-white rounded-2xl border border-gray-200 p-5"><div className="flex items-center justify-between mb-4"><div><p className="font-semibold">P&L by period</p><p className="text-xs text-gray-400 mt-1">Sales − discounts − refunds = net revenue; net revenue − COGS − expenses = net profit.</p></div></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-xs text-gray-400 bg-gray-50"><th className="px-3 py-3">Period</th><th className="px-3 py-3">Sales</th><th className="px-3 py-3">Discounts</th><th className="px-3 py-3">Refunds</th><th className="px-3 py-3">Net Revenue</th><th className="px-3 py-3">COGS</th><th className="px-3 py-3">Gross Profit</th><th className="px-3 py-3">Expenses</th><th className="px-3 py-3">Net Profit</th><th className="px-3 py-3">Margin</th></tr></thead><tbody>{data.series.map(s=><tr key={s.period} className="border-b border-gray-50"><td className="px-3 py-3">{s.period}</td><td className="px-3 py-3">{money(s.sales)}</td><td className="px-3 py-3">{money(s.discounts)}</td><td className="px-3 py-3">{money(s.refunds)}</td><td className="px-3 py-3 font-medium">{money(s.net_revenue)}</td><td className="px-3 py-3">{money(s.cogs)}</td><td className="px-3 py-3">{money(s.gross_profit)}</td><td className="px-3 py-3">{money(s.expenses)}</td><td className={`px-3 py-3 font-semibold ${s.net_profit<0?'text-red-600':'text-emerald-600'}`}>{money(s.net_profit)}</td><td className="px-3 py-3">{formatPct(s.profit_margin)}</td></tr>)}</tbody></table></div></div>
    <div className="bg-white rounded-2xl border border-gray-200 p-5 mt-5"><p className="font-semibold mb-4">Expense entries</p>{expenses.length===0?<p className="text-sm text-gray-400">No expense entries for this period.</p>:<div className="space-y-2">{expenses.map(e=><div key={e.id} className="flex items-center justify-between py-2 border-b border-gray-50"><div><p className="text-sm font-medium">{e.category}</p><p className="text-xs text-gray-400">{e.date} · {e.note || "No note"}</p></div><div className="flex items-center gap-3"><span className="font-semibold">{money(e.amount)}</span><button onClick={()=>removeExpense(e.id)} className="text-gray-400 hover:text-red-600"><Trash2 size={15}/></button></div></div>)}</div>}</div>
    {showExpense&&<Modal open title="Add business expense" onClose={()=>setShowExpense(false)}><div className="space-y-4"><Field label="Category"><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})} className={inputCls}>{["Shipping","Payment Gateway Fees","Marketing","Packaging","Platform Fees","Other Expenses"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Amount (₹)"><input type="number" min="0" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} className={inputCls}/></Field><Field label="Date"><input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})} className={inputCls}/></Field><Field label="Note"><input value={form.note} onChange={e=>setForm({...form,note:e.target.value})} className={inputCls}/></Field><div className="flex justify-end gap-2"><button onClick={()=>setShowExpense(false)} className="px-4 py-2 text-sm text-gray-600">Cancel</button><button onClick={saveExpense} disabled={saving} className="px-4 py-2 rounded-lg bg-plum text-white text-sm">{saving?"Saving…":"Add Expense"}</button></div></div></Modal>}
  </div>;
} 
